site_name: 'romario-golang-7777'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/romario-io/romario-golang-7777
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
